version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/app

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: backend
    environment:
      DB_HOST: db
      DB_DATABASE: grupoplan_db
      DB_USERNAME: root
    networks:
      - bridge-1
    ports:
      - "80:80"
    depends_on:
      - db
    # volumes:
    #   - ./backend:/app

  db:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: grupoplan_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - bridge-1
    ports:
      - "3306:3306"

networks:
  bridge-1:
    driver: bridge
